### ISSUE TITLE
Graphical bug in Reservation info popup

### ISSUE THREAD

**Issue by brocahontaz** [brocahontaz/2dv603-project#2]
Weird bug happening every other time, causing the Price text to be cut off, as well as all other text fields getting weird - pixelated, blurry, "double" font in black/red. And then it disappears when moving the mouse over the title bar of the titled pane, sometimes.

Hard to get to the root of the problem, since there are no exceptions getting caught that would point in the right direction. 

Big prio on solving this since it affects the user experience greatly in a negative way.

**Comment by fredden87** [comment]
Bug fixed! had to do with the ProgressIndicator and Platform.runLater conflicting in some way.

**Comment by brocahontaz** [comment]
Great solution, and excellent work finding the remedy to this mysterious bug!
